#!/usr/bin/env bash
#
# text-demo.sh --- Render a variety of QR codes as text into a single file.
#
# Demonstrates the two text styles of `clqr -f text`:
#   * Unicode (default): two module rows packed per line with half-block glyphs
#   * ASCII (--ascii):   two characters per module ("##" / "  ")
#
# Usage:  ./examples/text-demo.sh [output-file]
#         (defaults to examples/qr-codes.txt)

set -euo pipefail

# Locate the clqr binary (built by `make`), preferring the repo-local one.
here="$(cd "$(dirname "$0")/.." && pwd)"
clqr="${CLQR:-$here/bin/clqr}"
out="${1:-$here/examples/qr-codes.txt}"

if [[ ! -x "$clqr" ]]; then
  echo "clqr binary not found at $clqr -- run 'make' first (or set CLQR=...)." >&2
  exit 1
fi

# section LABEL DESCRIPTION  -- write a banner (to the file we are building)
section() {
  printf '\n============================================================\n'
  printf '  %s\n' "$1"
  printf '  %s\n' "$2"
  printf '============================================================\n\n'
}

# render DESCRIPTION -- run clqr with the remaining args, discarding its
# stderr summary line, and echo the description first.
render() {
  local desc="$1"; shift
  printf -- '--- %s\n\n' "$desc"
  "$clqr" "$@" 2>/dev/null
  printf '\n'
}

{
  cat <<'HEADER'
clqr text rendering demo
========================

Each block below is a scannable QR code drawn with text glyphs. Point a phone
camera or any QR reader at one. Viewed on a light background (the usual editor
default) the dark modules are the ink, which is the correct polarity.

  * Unicode style  -- compact half-block glyphs, two module rows per text line
  * ASCII style    -- "##" for dark and spaces for light, two chars per module
HEADER

  section "Unicode style (default)" "clqr -f text <content>"

  render 'URL, error correction M (default)' \
    -f text -b 2 'https://github.com/lispnik/clqr'

  render 'Alphanumeric, error correction Q' \
    -f text -b 2 -e q 'HELLO WORLD'

  render 'Numeric, forced version 2, error correction H' \
    -f text -b 2 -M numeric -V 2 -e h '01234567'

  render 'Kanji (Shift-JIS), error correction M' \
    -f text -b 2 -M kanji 'こんにちは世界'

  section "ASCII style (--ascii)" "clqr -f text --ascii <content>"

  render 'Short text, ASCII glyphs' \
    -f text --ascii -b 2 'clqr'

  render 'Numeric, ASCII glyphs, error correction L' \
    -f text --ascii -b 2 -e l '1234567890'

  section "Inverted (--invert)" "for light-on-dark terminals"

  render 'Same URL, inverted polarity' \
    -f text --invert -b 2 'https://github.com/lispnik/clqr'

  printf 'Generated by examples/text-demo.sh using clqr %s.\n' \
    "$("$clqr" --version 2>/dev/null | awk '{print $NF}')"
} > "$out"

echo "Wrote $out ($(wc -l < "$out") lines)."
