#!/usr/bin/env bash
#
# text-demo.sh --- Render a variety of QR codes as text into a single file.
#
# Demonstrates the two text styles of `clqr -f text`:
#   * Unicode (default): two module rows packed per line with half-block glyphs
#   * ASCII (--ascii):   two characters per module ("##" / "  ")
#
# Usage:  ./examples/text-demo.sh [output-file]
#         (defaults to examples/qr-codes.txt)
#
# Set CLQR to override the binary (an absolute path or a name on PATH).

set -euo pipefail

# Locate the repo root from this script, then the clqr binary.  BASH_SOURCE is
# used rather than $0 so it works when the script is sourced.
here="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
clqr="${CLQR:-$here/bin/clqr}"
out="${1:-$here/examples/qr-codes.txt}"

# `command -v` resolves both an absolute path (checking it is executable) and a
# bare command name on PATH, unlike a plain `-x` file test.
if ! command -v "$clqr" >/dev/null 2>&1; then
  if command -v clqr >/dev/null 2>&1; then
    clqr="clqr"
  else
    echo "clqr not found (looked at '$clqr' and PATH) -- run 'make' or set CLQR=..." >&2
    exit 1
  fi
fi

# Build into a temporary file and move it into place only on success, so a
# failure never leaves a truncated qr-codes.txt behind.
tmp="$(mktemp "${TMPDIR:-/tmp}/clqr-demo.XXXXXX")"
trap 'rm -f "$tmp"' EXIT

# A 4-module quiet zone (clqr's default) is what the QR spec requires for the
# codes to be reliably scannable, so we do not shrink it here.

# section LABEL DESCRIPTION -- write a banner.
section() {
  printf '\n============================================================\n'
  printf '  %s\n' "$1"
  printf '  %s\n' "$2"
  printf '============================================================\n\n'
}

# render DESCRIPTION [clqr args...] -- echo the description, then the code.
# clqr's one-line stderr summary is suppressed, but a genuine failure is caught
# explicitly (rather than being hidden by `set -e` + 2>/dev/null) and reported.
render() {
  local desc="$1"; shift
  printf -- '--- %s\n\n' "$desc"
  if ! "$clqr" "$@" 2>/dev/null; then
    echo "ERROR: clqr failed rendering '$desc' (args: $*)" >&2
    exit 1
  fi
  printf '\n'
}

{
  cat <<'HEADER'
clqr text rendering demo
========================

Each block below is a scannable QR code drawn with text glyphs. Point a phone
camera or any QR reader at one. Viewed on a light background (the usual editor
default) the dark modules are the ink, which is the correct polarity.

  * Unicode style  -- compact half-block glyphs, two module rows per text line
  * ASCII style    -- "##" for dark and spaces for light, two chars per module
HEADER

  section "Unicode style (default)" "clqr -f text <content>"

  render 'URL, error correction M (default)' \
    -f text 'https://github.com/lispnik/clqr'

  render 'Alphanumeric, error correction Q' \
    -f text -e q 'HELLO WORLD'

  render 'Numeric, forced version 2, error correction H' \
    -f text -M numeric -V 2 -e h '01234567'

  render 'Kanji (Shift-JIS), error correction M' \
    -f text -M kanji 'こんにちは世界'

  section "ASCII style (--ascii)" "clqr -f text --ascii <content>"

  render 'Short text, ASCII glyphs' \
    -f text --ascii 'clqr'

  render 'Numeric, ASCII glyphs, error correction L' \
    -f text --ascii -e l '1234567890'

  section "Inverted (--invert)" "for light-on-dark terminals"

  render 'Same URL, inverted polarity' \
    -f text --invert 'https://github.com/lispnik/clqr'

  printf 'Generated by examples/text-demo.sh -- re-run it to refresh this file.\n'
} > "$tmp"

mv "$tmp" "$out"
trap - EXIT
echo "Wrote $out ($(wc -l < "$out") lines)."
