;;;; galois.lisp --- GF(256) arithmetic and Reed-Solomon error correction.
;;;;
;;;; QR codes use the Galois field GF(2^8) generated by the primitive
;;;; polynomial x^8 + x^4 + x^3 + x^2 + 1 (0x11D) with primitive element 2, as
;;;; specified in ISO/IEC 18004 section 7.5.2.  This file builds the field
;;;; log/antilog tables at load time and implements Reed-Solomon codeword
;;;; generation on top of them.

(in-package #:clqr)

(defconstant +gf-primitive+ #x11D
  "The QR primitive polynomial x^8+x^4+x^3+x^2+1 as an integer.")

(declaim (type (simple-array (unsigned-byte 8) (256)) +gf-exp+))
(declaim (type (simple-array (unsigned-byte 16) (256)) +gf-log+))

(defparameter +gf-exp+
  (make-array 256 :element-type '(unsigned-byte 8) :initial-element 0)
  "Antilog table: +gf-exp+[i] = alpha^i in GF(256), for i in 0..255.")

(defparameter +gf-log+
  (make-array 256 :element-type '(unsigned-byte 16) :initial-element 0)
  "Log table: +gf-log+[x] = i such that alpha^i = x, for x in 1..255.")

(let ((x 1))
  (dotimes (i 255)
    (setf (aref +gf-exp+ i) x)
    (setf (aref +gf-log+ x) i)
    (setf x (ash x 1))
    (when (>= x 256)
      (setf x (logxor x +gf-primitive+))))
  ;; +gf-exp+[255] wraps to alpha^0 = 1, convenient for multiplication.
  (setf (aref +gf-exp+ 255) (aref +gf-exp+ 0)))

(declaim (inline gf-mul))
(defun gf-mul (a b)
  "Multiply A and B in GF(256)."
  (declare (type (unsigned-byte 8) a b))
  (if (or (zerop a) (zerop b))
      0
      (aref +gf-exp+ (mod (+ (aref +gf-log+ a) (aref +gf-log+ b)) 255))))

(defun rs-generator-polynomial (degree)
  "Return the Reed-Solomon generator polynomial of DEGREE as a vector of
GF(256) coefficients, highest power first, leading coefficient omitted-normalised
so the returned vector has DEGREE+1 coefficients with a leading 1.

The polynomial is the product of (x - alpha^i) for i in 0..degree-1."
  (declare (type (integer 1 255) degree))
  (let ((poly (make-array 1 :element-type '(unsigned-byte 8) :initial-element 1)))
    (dotimes (i degree)
      (let* ((root (aref +gf-exp+ i))
             (next (make-array (1+ (length poly))
                               :element-type '(unsigned-byte 8)
                               :initial-element 0)))
        ;; Multiply POLY by (x - alpha^i) = (x + alpha^i) in GF(2).  POLY is
        ;; stored highest power first, so the x term keeps the index and the
        ;; alpha^i (constant) term moves one index higher.
        (dotimes (j (length poly))
          (let ((c (aref poly j)))
            (setf (aref next j) (logxor (aref next j) c))
            (setf (aref next (1+ j)) (logxor (aref next (1+ j)) (gf-mul c root)))))
        (setf poly next)))
    poly))

(defun rs-encode (data ec-count)
  "Compute EC-COUNT Reed-Solomon error correction codewords for the data
codeword vector DATA (a sequence of (unsigned-byte 8)).  Returns a fresh
vector of EC-COUNT codewords."
  (declare (type (integer 1 255) ec-count))
  (let* ((data (coerce data '(simple-array (unsigned-byte 8) (*))))
         (gen (rs-generator-polynomial ec-count))
         ;; Remainder register, initially zero.
         (remainder (make-array ec-count
                                :element-type '(unsigned-byte 8)
                                :initial-element 0)))
    (loop for byte across data
          for factor = (logxor byte (aref remainder 0))
          do ;; Shift the remainder register left by one codeword.
             (loop for i from 0 below (1- ec-count)
                   do (setf (aref remainder i) (aref remainder (1+ i))))
             (setf (aref remainder (1- ec-count)) 0)
             ;; XOR in FACTOR * generator (skip generator's leading 1 term,
             ;; which corresponds to the codeword just shifted out).
             (unless (zerop factor)
               (dotimes (i ec-count)
                 (setf (aref remainder i)
                       (logxor (aref remainder i)
                               (gf-mul (aref gen (1+ i)) factor))))))
    remainder))
